### ISSUE TITLE
Change cursor on hover to indicate user he can type

### ISSUE THREAD

**Issue by stephanie-walter** [dcneiner/In-Field-Labels-jQuery-Plugin#36]
Hi :)

A great thing to add to the CSS would be

``` css
label:hover{
    cursor:text;
}
```

so that the user would get the text cursor (like a "real" placeholder) when he hovers the field.
