### ISSUE TITLE
Labels not fading in IE 7

### ISSUE THREAD

**Issue by jhig85** [dcneiner/In-Field-Labels-jQuery-Plugin#46]
Hello everyone,

I am having issues getting the labels to fade out in IE 7. It works in IE 8 & 9 but for whatever reason won't fade in IE 7. Here is the CSS I am using in my IE 7 stylesheet:

``` css
form p label{
    font-size:1.2em;
    font-family:Arial, Helvetica, sans-serif;
    color:#a7a6a6;
    position:absolute;
    top:20px;
    left:5px;
    display:inline-block;
    }
form p input{
    width:46.25%;
    border-radius:2px;
    background:#fff;
    border:1px solid #ccc;
    font-size:1.2em;
    font-family:Arial, Helvetica, sans-serif;
    margin-top:10px;
    padding:1px 1%;
    color:#999;
    display:inline-block;
    }
```

Here is a URL: http://www2.claytonhomes.com/clayton-lp-v1 
I am using the basic jquery file. Any help would be awesome. Thanks!
